#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -d $DIR/venv ]; then

	echo "Install Gazua~~~!!!"
	echo "Install path: $DIR"

	virtualenv $DIR/venv
fi

source $DIR/venv/bin/activate

pip_path="$(which pip)"
if [ -z $pip_path ]; then
	echo "Failed to install: not installed pip"
	exit 1
fi

is_npyscreen_installed="$(pip freeze | grep npyscreen)"

if [ -z $is_npyscreen_installed ]; then
	pip install -r requirements.txt
fi


python $DIR/gz.py
