#!/bin/bash

if [ ! -d ./venv ]; then
	python_path="$(which python3)"
	if [ -z $python_path ]; then
		echo "not exists python3"
		exit 1
	fi

	virtualenv venv -p $python_path
	source ./venv/bin/activate

	pip install npyscreen
fi

source ./venv/bin/activate

python ./gz.py
